#! /usr/bin/perl

die "Usage: $0 <ifname> <hostname>\n"
    unless @ARGV == 2;
my ($ifname, $hostname) = @ARGV;

my $addr = `LC_ALL=C /sbin/ifconfig $ifname | /usr/bin/perl -we '/inet ([0-9.]+) / and print \$1 for <>'`
    or die "could not obtain IPv4 address of interface $ifname";

my $hosts = '';

open my $fh, '<', '/etc/hosts'
    or die "could not open /etc/hosts:$!";
while (my $line = <$fh>) {
    chomp $line;
    if ($line =~ /^([0-9.]+)\s+$hostname$/) {
        # exit now if there's no need for a rewrite
        exit 0 if $addr eq $1;
        # found, skip
    } else {
        $hosts .= "$line\n";
    }
}
close $fh;

$hosts .= "$addr $hostname\n";

open my $fh, '>', '/etc/hosts.new'
    or die "failed to open /etc/hosts.new:$!";
print $fh $hosts;
close $fh;

rename '/etc/hosts.new', '/etc/hosts'
    or die "failed to rename /etc/hosts.new to /etc/hosts:$!";
